import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { Memory, MemoryAlbum } from "../features/memories/model/memory.types";
import { hasFamilyPermission } from "../features/family/permissions/familyPermissions";
import { getCurrentFamilyMember, useFamilyStore } from "./familyStore";
const automaticAlbums: MemoryAlbum[] = ["growth","vacations","milestones","vaccinations","birthdays"].map((id)=>({id:`automatic:${id}`,name:id,nameKey:`memories.albums.${id}`,kind:"automatic",tags:[id],createdAt:new Date().toISOString()}));
interface MemoryStore { memories:Memory[];albums:MemoryAlbum[];dismissedAutomaticKeys:string[];upsertMemory:(memory:Memory)=>void;upsertAutomatic:(memory:Memory)=>void;deleteMemory:(id:string)=>void;toggleFavorite:(id:string)=>void;addAlbum:(name:string,tags:string[])=>void; }
const canManage=()=>hasFamilyPermission(getCurrentFamilyMember(),"canManageMemories");
function audit(memory:Memory,action:"created"|"updated"|"deleted"){const member=getCurrentFamilyMember();if(member)useFamilyStore.getState().addAudit({memberId:member.id,action,entityType:"memory",entityId:memory.id,descriptionKey:`family.audit.memory.${action}`,metadata:{title:memory.title}})}
export const useMemoryStore=create<MemoryStore>()(persist((set,get)=>({memories:[],albums:automaticAlbums,dismissedAutomaticKeys:[],upsertMemory:(memory)=>{if(!canManage())return;const exists=get().memories.some(item=>item.id===memory.id);set(state=>({memories:exists?state.memories.map(item=>item.id===memory.id?{...memory,updatedAt:new Date().toISOString()}:item):[memory,...state.memories]}));audit(memory,exists?"updated":"created")},upsertAutomatic:(memory)=>set(state=>state.dismissedAutomaticKeys.includes(memory.automaticSourceKey??"")||state.memories.some(item=>item.automaticSourceKey===memory.automaticSourceKey)?state:{memories:[memory,...state.memories]}),deleteMemory:(id)=>{if(!canManage())return;const memory=get().memories.find(item=>item.id===id);if(!memory)return;set(state=>({memories:state.memories.filter(item=>item.id!==id),dismissedAutomaticKeys:memory.automaticSourceKey?[...new Set([...state.dismissedAutomaticKeys,memory.automaticSourceKey])]:state.dismissedAutomaticKeys}));audit(memory,"deleted")},toggleFavorite:(id)=>{if(!canManage())return;set(state=>({memories:state.memories.map(item=>item.id===id?{...item,favorite:!item.favorite,updatedAt:new Date().toISOString()}:item)}))},addAlbum:(name,tags)=>{if(!canManage()||!name.trim())return;set(state=>({albums:[...state.albums,{id:crypto.randomUUID(),name:name.trim(),kind:"custom",tags,createdAt:new Date().toISOString()}]}))}}),{name:"babynest-memories",version:1}));
