import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { Activity } from "../entities/activity/model/activity.types";
import type { Baby } from "../entities/baby/model/baby.types";
import type { Reminder, ReminderEvent } from "../entities/reminder/reminder.types";
import { calculateActivityAwareReminderState, calculateNextTrigger, isValidSchedule } from "../features/reminders/utils/reminderSchedule";
import { getRoutinePreferences } from "../features/routine/utils/routineIntervals";

interface ReminderStore { reminders: Reminder[]; events: ReminderEvent[]; addReminder: (reminder: Reminder, activities?: Activity[]) => boolean; updateReminder: (id: string, updates: Partial<Reminder>, activities?: Activity[]) => boolean; deleteReminder: (id: string) => void; toggleReminder: (id: string, activities?: Activity[]) => void; markTriggered: (id: string, status: ReminderEvent["status"], at?: Date, activities?: Activity[]) => void; calculateNextTrigger: (id: string, activities?: Activity[]) => string | undefined; synchronizeActivityAwareReminders: (activities: Activity[], babies?: Baby[], now?: Date) => number; setNextTrigger: (id: string, nextTriggerAt: string) => void; clearRemindersForBaby: (babyId: string) => void; clearHistory: () => void }

function normalizeReminder(reminder: Reminder) { if (!reminder.id || !reminder.babyId || !reminder.title.trim() || !isValidSchedule(reminder.schedule)) return null; return { ...reminder, enabled: Boolean(reminder.enabled), activityAware: Boolean(reminder.activityAware) }; }

export const useReminderStore = create<ReminderStore>()(persist((set, get) => ({
  reminders: [], events: [],
  addReminder: (reminder, activities = []) => { if (get().reminders.some((item) => item.id === reminder.id)) return false; const valid = normalizeReminder(reminder); if (!valid) return false; const nextTriggerAt = calculateNextTrigger(valid, new Date(), activities); set((state) => ({ reminders: [...state.reminders, { ...valid, nextTriggerAt }] })); return true; },
  updateReminder: (id, updates, activities = []) => { const current = get().reminders.find((item) => item.id === id); if (!current) return false; const valid = normalizeReminder({ ...current, ...updates, id: current.id, babyId: updates.babyId ?? current.babyId, updatedAt: new Date().toISOString() }); if (!valid) return false; const nextTriggerAt = calculateNextTrigger({ ...valid, lastTriggeredAt: undefined }, new Date(), activities); set((state) => ({ reminders: state.reminders.map((item) => item.id === id ? { ...valid, lastTriggeredAt: undefined, nextTriggerAt } : item) })); return true; },
  deleteReminder: (id) => set((state) => ({ reminders: state.reminders.filter((item) => item.id !== id) })),
  toggleReminder: (id, activities = []) => set((state) => ({ reminders: state.reminders.map((item) => item.id === id ? (() => { const enabled = !item.enabled; return { ...item, enabled, updatedAt: new Date().toISOString(), nextTriggerAt: enabled ? calculateNextTrigger({ ...item, enabled }, new Date(), activities) : item.nextTriggerAt }; })() : item) })),
  markTriggered: (id, status, at = new Date(), activities = []) => set((state) => ({ reminders: state.reminders.map((item) => item.id === id ? { ...item, lastTriggeredAt: at.toISOString(), nextTriggerAt: calculateNextTrigger({ ...item, lastTriggeredAt: at.toISOString() }, at, activities, true), enabled: item.schedule.kind === "one-time" ? false : item.enabled, updatedAt: at.toISOString() } : item), events: [{ id: crypto.randomUUID(), reminderId: id, babyId: state.reminders.find((item) => item.id === id)?.babyId ?? "", triggeredAt: at.toISOString(), status }, ...state.events].slice(0, 50) })),
  calculateNextTrigger: (id, activities = []) => { const reminder = get().reminders.find((item) => item.id === id); return reminder ? calculateNextTrigger(reminder, new Date(), activities) : undefined; },
  synchronizeActivityAwareReminders: (activities, babies = [], now = new Date()) => { const state = get(); let changed = 0; const updatedAt = now.toISOString(); const reminders = state.reminders.map((reminder) => { const routine=getRoutinePreferences(babies.find(baby=>baby.id===reminder.babyId)?.routinePreferences);const routineInterval=reminder.type==="feeding"?routine.feedingIntervalMinutes:reminder.type==="diaper"?routine.diaperIntervalMinutes:undefined;const result = calculateActivityAwareReminderState(reminder, activities, now, routineInterval); if (!result) return reminder; const same = reminder.nextTriggerAt === result.nextTriggerAt && reminder.referenceActivityId === result.referenceActivityId && reminder.referenceAt === result.referenceAt && reminder.referenceSource === result.referenceSource; if (same) return reminder; changed += 1; return { ...reminder, ...result, updatedAt }; }); if (changed > 0) set({ reminders }); return changed; },
  setNextTrigger: (id, nextTriggerAt) => set((state) => ({ reminders: state.reminders.map((reminder) => reminder.id === id ? { ...reminder, nextTriggerAt } : reminder) })),
  clearRemindersForBaby: (babyId) => set((state) => ({ reminders: state.reminders.filter((item) => item.babyId !== babyId), events: state.events.filter((event) => event.babyId !== babyId) })),
  clearHistory: () => set({ events: [] }),
}), { name: "babynest-reminders", version: 1, migrate: (persisted) => { const value = persisted as Partial<ReminderStore> | undefined; return { reminders: (value?.reminders ?? []).map(normalizeReminder).filter(Boolean), events: (value?.events ?? []).slice(0, 50) }; } }));
