import {create} from "zustand";
import {persist} from "zustand/middleware";
import type {Baby,SupportedVaccinationCountryCode} from "../entities/baby/model/baby.types";
import type {VaccinationRecord} from "../features/vaccinations/model/vaccination.types";
import type {VaccinationScheduleConflict,VaccinationScheduleReconciliationResult} from "../features/vaccinations/utils/reconcileVaccinationSchedule";
import {reconcileVaccinationSchedule} from "../features/vaccinations/utils/reconcileVaccinationSchedule";
import {generateVaccinationSchedule} from "../features/vaccinations/utils/vaccinationSchedule";
import {hasFamilyPermission} from "../features/family/permissions/familyPermissions";
import {getCurrentFamilyMember,useFamilyStore} from "./familyStore";

interface VaccinationStore{records:VaccinationRecord[];conflicts:VaccinationScheduleConflict[];replaceRecords:(records:VaccinationRecord[],conflicts?:VaccinationScheduleConflict[])=>void;synchronizeBabies:(babies:Baby[])=>void;previewCountryChange:(baby:Baby|undefined,next:SupportedVaccinationCountryCode,nextRegionCode?:string)=>VaccinationScheduleReconciliationResult;applyCountryChange:(baby:Baby|undefined,next:SupportedVaccinationCountryCode,nextRegionCode?:string)=>VaccinationScheduleReconciliationResult;updateRecord:(id:string,updates:Partial<VaccinationRecord>)=>void;deleteCompletion:(id:string)=>void;clearForBaby:(babyId:string)=>void;dismissConflict:(id:string)=>void}
const normalize=(record:VaccinationRecord):VaccinationRecord=>({...record,scheduleCountryCode:record.scheduleCountryCode??record.scheduleCountry??"BG",scheduleItemId:record.scheduleItemId??record.vaccineCode,recordOrigin:record.recordOrigin??"generated"});
const emptyReconciliation=():VaccinationScheduleReconciliationResult=>({preservedRecords:[],newPlannedRecords:[],removedPlannedRecordIds:[],conflicts:[],summary:{preservedCompleted:0,preservedManual:0,addedPlanned:0,removedPlanned:0}});
const canManage=()=>hasFamilyPermission(getCurrentFamilyMember(),"canManageVaccinations");
const auditVaccination=(record:VaccinationRecord,action:"updated"|"deleted")=>{const member=getCurrentFamilyMember();if(member)useFamilyStore.getState().addAudit({memberId:member.id,action,entityType:"vaccination",entityId:record.id,descriptionKey:`family.audit.vaccination.${action}`})};
export const useVaccinationStore=create<VaccinationStore>()(persist((set,get)=>({
 records:[],conflicts:[],replaceRecords:(records,conflicts=[])=>set({records:records.map(normalize),conflicts}),
 synchronizeBabies:(babies)=>set(state=>{const valid=new Set(babies.map(b=>b.id)),existing=state.records.map(normalize).filter(r=>valid.has(r.babyId));const generated=babies.flatMap(b=>{const profile=b.vaccinationProfile;if(!profile||profile.countryCode==="OTHER"||existing.some(record=>record.babyId===b.id&&record.recordOrigin==="generated"))return[];return generateVaccinationSchedule(b,profile.countryCode,new Date(),profile.regionCode)});return{records:[...existing,...generated],conflicts:state.conflicts.filter(c=>existing.some(r=>r.id===c.existingRecordId))}}),
 previewCountryChange:(baby,next,nextRegionCode)=>baby?reconcileVaccinationSchedule({baby,previousCountryCode:baby.vaccinationProfile?.countryCode??"BG",nextCountryCode:next,nextRegionCode,existingRecords:get().records,now:new Date()}):emptyReconciliation(),
 applyCountryChange:(baby,next,nextRegionCode)=>{const result=get().previewCountryChange(baby,next,nextRegionCode);if(!baby||!canManage())return result;set(state=>({records:[...state.records.filter(r=>r.babyId!==baby.id),...result.preservedRecords,...result.newPlannedRecords],conflicts:[...state.conflicts.filter(c=>!result.preservedRecords.some(r=>r.id===c.existingRecordId)),...result.conflicts]}));return result},
 updateRecord:(id,updates)=>{if(!canManage())return;const record=get().records.find(item=>item.id===id);set(state=>({records:state.records.map(record=>record.id===id?{...record,...updates,id:record.id,babyId:record.babyId,updatedAt:new Date().toISOString()}:record)}));if(record)auditVaccination(record,"updated")},
 deleteCompletion:(id)=>{if(!canManage())return;const record=get().records.find(item=>item.id===id);set(state=>({records:state.records.map(record=>record.id===id?{...record,status:"upcoming",administeredDate:undefined,manufacturer:undefined,batchNumber:undefined,doctor:undefined,clinic:undefined,reaction:undefined,notes:undefined,updatedAt:new Date().toISOString()}:record)}));if(record)auditVaccination(record,"deleted")},
 clearForBaby:(babyId)=>set(state=>({records:state.records.filter(r=>r.babyId!==babyId),conflicts:state.conflicts.filter(c=>!state.records.some(r=>r.id===c.existingRecordId&&r.babyId===babyId))})),dismissConflict:(id)=>set(state=>({conflicts:state.conflicts.map(c=>c.id===id?{...c,dismissed:true}:c)}))
}),{name:"babynest-vaccinations",version:2,migrate:(persisted)=>{const state=persisted as Partial<VaccinationStore>|undefined;return{records:(state?.records??[]).map(normalize),conflicts:state?.conflicts??[]}}}));
