import type { Activity, MedicineActivity } from "../../../entities/activity/model/activity.types";
import type { Reminder } from "../../../entities/reminder/reminder.types";
import type { StatisticsSnapshot } from "../../utils/statistics";
import type { SleepPrediction } from "../../sleep/prediction/sleepPrediction.types";
import { calculateNextDiaperStatus, calculateNextFeedingStatus } from "../../routine/utils/nextRoutineStatus";
import type { RoutineConfidence, RoutineSource } from "../../routine/model/routine.types";

export type DashboardTone = "positive" | "attention" | "critical" | "neutral";
export type DashboardTrend = "better" | "normal" | "lower" | "none";
export interface DashboardSignal { tone: DashboardTone; labelKey: string; params?: Record<string, string | number> }
export interface SleepAnalysis { signal: DashboardSignal; trend: DashboardTrend; currentWakeSeconds: number | null; nextNapAt: Date | null }
export interface FeedingAnalysis { signal: DashboardSignal; trend: DashboardTrend; count: number; breastfeedingCount: number; bottleAverageMl: number; latestAt: Date | null; secondsSinceLatest: number | null; intervalMinutes: number; nextAt: Date | null; remainingSeconds:number|null; overdueSeconds:number; source:RoutineSource;sampleSize:number;confidence:RoutineConfidence }
export interface DiaperAnalysis { signal: DashboardSignal; trend: DashboardTrend; total: number; wet: number; dirty: number; mixed: number; latestAt: Date | null; secondsSinceLatest: number | null; intervalMinutes:number; nextAt: Date | null; remainingSeconds:number|null;overdueSeconds:number;source:RoutineSource;sampleSize:number;confidence:RoutineConfidence }
export interface HealthAnalysis { signal: DashboardSignal; nextMedicineAt: Date | null; medicineCount: number }

function countTrend(today: number, recentDailyAverage: number): DashboardTrend { if (!recentDailyAverage) return today ? "better" : "none"; const ratio=today/recentDailyAverage; return ratio>1.2?"better":ratio<0.8?"lower":"normal"; }

export function analyzeSleep(today: StatisticsSnapshot, recent: StatisticsSnapshot, prediction: SleepPrediction, latestSleepEndedAt: Date | null, activeSleep: boolean, now: Date): SleepAnalysis {
  const recentDays=Math.max(1,recent.dailySeries.length-1); const recentAverage=recent.dailySeries.slice(0,-1).reduce((sum,day)=>sum+day.sleepMilliseconds,0)/recentDays; const trend=countTrend(today.totalSleepMilliseconds,recentAverage);
  const currentWakeSeconds=!activeSleep&&latestSleepEndedAt?Math.max(0,Math.floor((now.getTime()-latestSleepEndedAt.getTime())/1000)):null;
  let signal:DashboardSignal={tone:"neutral",labelKey:"dashboard.ai.sleepNoData"};
  if(activeSleep)signal={tone:"positive",labelKey:"dashboard.ai.sleepingNow"}; else if(prediction.isOverdue)signal={tone:"critical",labelKey:"dashboard.ai.napOverdue"}; else if(prediction.countdownSeconds!==null&&prediction.countdownSeconds<=30*60)signal={tone:"attention",labelKey:"dashboard.ai.napSoon"}; else if(today.totalSleepMilliseconds>0&&trend==="better")signal={tone:"positive",labelKey:"dashboard.ai.sleepGood"}; else if(today.totalSleepMilliseconds>0)signal={tone:"positive",labelKey:"dashboard.ai.sleepStable"};
  return {signal,trend,currentWakeSeconds,nextNapAt:activeSleep?null:prediction.nextSleepAt};
}

export function analyzeFeeding(activities: Activity[], babyId:string, today: StatisticsSnapshot, recent: StatisticsSnapshot, now: Date, configuredIntervalMinutes:number,useAdaptiveInterval:boolean): FeedingAnalysis {
  const routine=calculateNextFeedingStatus({activities,babyId,now,configuredIntervalMinutes,useAdaptiveInterval});const latestAt=routine.lastActivityAt; const secondsSinceLatest=latestAt?Math.floor((now.getTime()-latestAt.getTime())/1000):null; const recentAverage=recent.dailySeries.slice(0,-1).reduce((sum,day)=>sum+day.feedingCount,0)/Math.max(1,recent.dailySeries.length-1); const trend=countTrend(today.totalFeedings,recentAverage); let signal:DashboardSignal={tone:"neutral",labelKey:"dashboard.ai.feedingNoData"}; if(routine.overdueSeconds>0)signal={tone:"critical",labelKey:"dashboard.ai.feedingOverdue"}; else if(routine.remainingSeconds!==null&&routine.remainingSeconds<=routine.intervalMinutes*60*.2)signal={tone:"attention",labelKey:"dashboard.ai.feedingLonger"}; else if(today.totalFeedings>0)signal={tone:"positive",labelKey:"dashboard.ai.feedingConsistent"}; return {signal,trend,count:today.totalFeedings,breastfeedingCount:today.breastfeedingCount,bottleAverageMl:today.averageBottleAmountMl,latestAt,secondsSinceLatest,intervalMinutes:routine.intervalMinutes,nextAt:routine.nextAt,remainingSeconds:routine.remainingSeconds,overdueSeconds:routine.overdueSeconds,source:routine.source,sampleSize:routine.sampleSize,confidence:routine.confidence};
}

export function analyzeDiapers(activities: Activity[],babyId:string, today: StatisticsSnapshot, recent: StatisticsSnapshot, now: Date,configuredIntervalMinutes:number,useAdaptiveInterval:boolean): DiaperAnalysis {
  const routine=calculateNextDiaperStatus({activities,babyId,now,configuredIntervalMinutes,useAdaptiveInterval});const latestAt=routine.lastActivityAt; const secondsSinceLatest=latestAt?Math.floor((now.getTime()-latestAt.getTime())/1000):null; const recentAverage=recent.dailySeries.slice(0,-1).reduce((sum,day)=>sum+day.diaperCount,0)/Math.max(1,recent.dailySeries.length-1); const trend=countTrend(today.totalDiapers,recentAverage); let signal:DashboardSignal={tone:"neutral",labelKey:"dashboard.ai.diaperNoData"}; if(routine.overdueSeconds>0)signal={tone:"critical",labelKey:"dashboard.ai.diaperOverdue"}; else if(routine.remainingSeconds!==null&&routine.remainingSeconds<=routine.intervalMinutes*60*.2)signal={tone:"attention",labelKey:"dashboard.ai.diaperSoon"}; else if(today.totalDiapers>0)signal={tone:"positive",labelKey:"dashboard.ai.diaperNormal"}; return {signal,trend,total:today.totalDiapers,wet:today.wetDiapers,dirty:today.dirtyDiapers,mixed:today.mixedDiapers,latestAt,secondsSinceLatest,intervalMinutes:routine.intervalMinutes,nextAt:routine.nextAt,remainingSeconds:routine.remainingSeconds,overdueSeconds:routine.overdueSeconds,source:routine.source,sampleSize:routine.sampleSize,confidence:routine.confidence};
}

export function analyzeHealth(activities: Activity[], reminders: Reminder[], babyId: string, now: Date): HealthAnalysis { const medicines=activities.filter((activity):activity is MedicineActivity=>activity.type==="medicine"&&activity.babyId===babyId&&!Number.isNaN(new Date(activity.startedAt).getTime())&&new Date(activity.startedAt)<=now); const todayStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()); const medicineCount=medicines.filter(item=>new Date(item.startedAt)>=todayStart).length; const next=reminders.filter(item=>item.babyId===babyId&&item.type==="medicine"&&item.enabled&&item.nextTriggerAt&&!Number.isNaN(new Date(item.nextTriggerAt).getTime())).sort((a,b)=>new Date(a.nextTriggerAt!).getTime()-new Date(b.nextTriggerAt!).getTime())[0]; const nextMedicineAt=next?.nextTriggerAt?new Date(next.nextTriggerAt):null; const seconds=nextMedicineAt?(nextMedicineAt.getTime()-now.getTime())/1000:null; const signal:DashboardSignal=seconds!==null&&seconds<=0?{tone:"critical",labelKey:"dashboard.ai.medicineDue"}:seconds!==null&&seconds<=3600?{tone:"attention",labelKey:"dashboard.ai.medicineSoon"}:medicineCount?{tone:"positive",labelKey:"dashboard.ai.medicineCompleted"}:{tone:"neutral",labelKey:"dashboard.ai.noHealthEvents"}; return {signal,nextMedicineAt,medicineCount}; }

export function generateDashboardInsight(health:HealthAnalysis,sleep:SleepAnalysis,feeding:FeedingAnalysis,diapers:DiaperAnalysis):DashboardSignal { if(health.signal.tone==="critical"||health.signal.tone==="attention")return health.signal;if(sleep.signal.tone==="critical"||sleep.signal.tone==="attention")return sleep.signal;if(feeding.signal.tone==="critical"||feeding.signal.tone==="attention")return feeding.signal;if(diapers.signal.tone==="critical"||diapers.signal.tone==="attention")return diapers.signal;return {tone:"positive",labelKey:"dashboard.ai.excellentDay"}; }
export function calculateBabyStatus(signals:DashboardSignal[]):DashboardSignal { if(signals.some(item=>item.tone==="critical"))return {tone:"critical",labelKey:"dashboard.ai.statusNeedsAttention"};if(signals.some(item=>item.tone==="attention"))return {tone:"attention",labelKey:"dashboard.ai.statusAttention"};if(signals.some(item=>item.tone==="positive"))return {tone:"positive",labelKey:"dashboard.ai.statusNormal"};return {tone:"neutral",labelKey:"dashboard.ai.statusNoData"}; }
