import { Baby, Milk, Timer } from "lucide-react";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import BreastfeedingCard from "../../../components/activity/BreastfeedingCard";
import QuickAddLauncher from "../../../components/activity/QuickAddLauncher";
import FeaturePageHeader from "../../../components/feature/FeaturePageHeader";
import FeatureHistorySection from "../../../components/feature/FeatureHistorySection";
import MetricCard from "../../../components/feature/MetricCard";
import PremiumGate from "../../../components/premium/PremiumGate";
import { useActivityStore } from "../../../store/activityStore";
import { useBabyStore } from "../../../store/babyStore";
import { buildStatisticsSnapshot, formatDurationLabel, type StatisticsPeriod } from "../../utils/statistics";
import { getStatisticsRange } from "../../statistics/utils/statisticsPeriod";
import { buildDailyFeedingChartData } from "../../statistics/utils/chartData";
import StatisticsCharts from "../../statistics/components/StatisticsCharts";
import StatisticsTabs from "../../statistics/components/StatisticsTabs";

export default function FeedingPage() {
  const { t, i18n } = useTranslation(); const [period,setPeriod]=useState<StatisticsPeriod>("7d"); const babies=useBabyStore(s=>s.babies); const selectedBabyId=useBabyStore(s=>s.selectedBabyId); const all=useActivityStore(s=>s.activities); const baby=babies.find(b=>b.id===selectedBabyId)??null;
  const activities=useMemo(()=>selectedBabyId?all.filter(a=>a.babyId===selectedBabyId):[],[all,selectedBabyId]); const now=new Date(); const range=getStatisticsRange(period,now); const stats=buildStatisticsSnapshot(activities,period,now); const feeds=activities.filter(a=>(a.type==="bottle"||a.type==="breastfeeding")&&!Number.isNaN(new Date(a.startedAt).getTime())).sort((a,b)=>new Date(b.startedAt).getTime()-new Date(a.startedAt).getTime());
  const fmt=(ms:number)=>formatDurationLabel(ms,i18n.language); const breastMs=stats.leftBreastMilliseconds+stats.rightBreastMilliseconds; const totalBottle=stats.dailySeries.reduce((s,d)=>s+d.bottleAmountMl,0); const totalSides=Math.max(1,breastMs); const chart=buildDailyFeedingChartData(stats.dailySeries,d=>new Intl.DateTimeFormat(i18n.language==="bg"?"bg-BG":"en-GB",{day:"numeric",month:"short"}).format(d));
  const charts=<section className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800 sm:p-6"><h2 className="text-xl font-bold text-slate-900 dark:text-white">{t("feedingPage.charts")}</h2><div className="mt-5 grid gap-6 xl:grid-cols-2"><StatisticsCharts data={chart} series={[{dataKey:"feedingCount",label:t("feedingPage.feedCount"),className:"bg-pink-500"}]} hasRecords={stats.totalFeedings>0} emptyLabel={t("feedingPage.noFeeds")} zeroLabel={t("statistics.zeroChartData")}/><StatisticsCharts data={chart} series={[{dataKey:"bottleMl",label:t("statistics.bottleAmountChart"),className:"bg-emerald-500",formatValue:v=>`${v} ml`},{dataKey:"breastfeedingMinutes",label:t("statistics.averageFeedingDuration"),className:"bg-violet-500",formatValue:v=>fmt(v*60000)}]} hasRecords={stats.totalFeedings>0} emptyLabel={t("feedingPage.noFeeds")} zeroLabel={t("statistics.zeroChartData")}/></div></section>;
  return <main className="space-y-6"><FeaturePageHeader icon={Milk} title={t("feedingPage.title")} description={t("feedingPage.description")} babyName={baby?.name??null} latest={feeds[0]?t("feedingPage.latest",{date:new Intl.DateTimeFormat(i18n.language,{dateStyle:"medium",timeStyle:"short"}).format(new Date(feeds[0].startedAt))}):t("feedingPage.noFeeds")}/><StatisticsTabs period={period} onChange={setPeriod}/><div className="grid gap-6 xl:grid-cols-2"><BreastfeedingCard/><QuickAddLauncher allowedTypes={["bottle"]}/></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={t("statistics.totalFeedings")} value={String(stats.totalFeedings)} icon={<Baby className="h-4 w-4"/>}/><MetricCard label={t("feedingPage.breastSessions")} value={String(stats.breastfeedingCount)} hint={t("feedingPage.totalDuration",{duration:fmt(breastMs)})}/><MetricCard label={t("feedingPage.bottles")} value={String(stats.bottleCount)} hint={t("feedingPage.totalVolume",{amount:totalBottle})}/><MetricCard label={t("statistics.averageBottleAmount")} value={`${stats.averageBottleAmountMl} ml`}/><MetricCard label={t("feedingPage.averageBreast")} value={stats.breastfeedingCount?fmt(breastMs/stats.breastfeedingCount):"—"} icon={<Timer className="h-4 w-4"/>}/><MetricCard label={t("statistics.leftBreast")} value={fmt(stats.leftBreastMilliseconds)} hint={`${Math.round(stats.leftBreastMilliseconds/totalSides*100)}%`}/><MetricCard label={t("statistics.rightBreast")} value={fmt(stats.rightBreastMilliseconds)} hint={`${Math.round(stats.rightBreastMilliseconds/totalSides*100)}%`}/></div><PremiumGate title={t("feedingPage.premiumTitle")} description={t("feedingPage.premiumDescription")} preview={charts}>{charts}</PremiumGate><FeatureHistorySection activities={activities} types={["breastfeeding","bottle"]} range={range} title={t("feedingPage.history")}/></main>;
}
