import { Bath, HeartPulse, Icon, Pill } from "lucide-react";
import { diaper } from "@lucide/lab";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import QuickAddLauncher from "../../../components/activity/QuickAddLauncher";
import FeaturePageHeader from "../../../components/feature/FeaturePageHeader";
import FeatureHistorySection from "../../../components/feature/FeatureHistorySection";
import MetricCard from "../../../components/feature/MetricCard";
import PremiumGate from "../../../components/premium/PremiumGate";
import type { BathActivity, MedicineActivity } from "../../../entities/activity/model/activity.types";
import { useActivityStore } from "../../../store/activityStore";
import { useBabyStore } from "../../../store/babyStore";
import { type StatisticsPeriod, formatDurationLabel } from "../../utils/statistics";
import StatisticsTabs from "../../statistics/components/StatisticsTabs";
import { getDiaperPeriodStats, getLiveDiaperStatus } from "../../statistics/utils/diaperInsights";
import { getStatisticsRange } from "../../statistics/utils/statisticsPeriod";

export default function HealthPage() {
  const { t,i18n }=useTranslation(); const [period,setPeriod]=useState<StatisticsPeriod>("7d"); const babies=useBabyStore(s=>s.babies); const selectedBabyId=useBabyStore(s=>s.selectedBabyId); const all=useActivityStore(s=>s.activities); const baby=babies.find(b=>b.id===selectedBabyId)??null;
  const activities=useMemo(()=>selectedBabyId?all.filter(a=>a.babyId===selectedBabyId):[],[all,selectedBabyId]); const now=new Date(); const range=getStatisticsRange(period,now); const historical=getDiaperPeriodStats(activities,selectedBabyId,range); const live=getLiveDiaperStatus(all,selectedBabyId,range,now); const inRange=(date:string)=>{const time=new Date(date).getTime();return Number.isFinite(time)&&time>=range.start.getTime()&&time<range.end.getTime()};
  const medicine=activities.filter((a):a is MedicineActivity=>a.type==="medicine"&&!Number.isNaN(new Date(a.startedAt).getTime())).sort((a,b)=>new Date(b.startedAt).getTime()-new Date(a.startedAt).getTime()); const baths=activities.filter((a):a is BathActivity=>a.type==="bath"&&!Number.isNaN(new Date(a.startedAt).getTime())).sort((a,b)=>new Date(b.startedAt).getTime()-new Date(a.startedAt).getTime()); const periodMedicine=medicine.filter(a=>inRange(a.startedAt)); const periodBaths=baths.filter(a=>inRange(a.startedAt)); const bathIntervals=periodBaths.slice(1).map((a,i)=>new Date(periodBaths[i].startedAt).getTime()-new Date(a.startedAt).getTime()).filter(v=>v>=0); const bathAverage=bathIntervals.length?bathIntervals.reduce((s,v)=>s+v,0)/bathIntervals.length:null;
  const fmt=(ms:number)=>formatDurationLabel(ms,i18n.language); const date=(value:string)=>new Intl.DateTimeFormat(i18n.language,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)); const latestCandidates=activities.filter(a=>["diaper","medicine","bath"].includes(a.type)&&!Number.isNaN(new Date(a.startedAt).getTime())).sort((a,b)=>new Date(b.startedAt).getTime()-new Date(a.startedAt).getTime());
  const advanced=<section className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800 sm:p-6"><h2 className="text-xl font-bold text-slate-900 dark:text-white">{t("healthPage.insights")}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><p className="rounded-2xl bg-amber-50 p-4 text-sm text-slate-700 dark:bg-amber-950/30 dark:text-slate-200">{historical.averageIntervalSeconds!==null?t("healthPage.averageDiaperInsight",{duration:fmt(historical.averageIntervalSeconds*1000)}):t("healthPage.moreDiaperData")}</p><p className="rounded-2xl bg-sky-50 p-4 text-sm text-slate-700 dark:bg-sky-950/30 dark:text-slate-200">{periodBaths[0]?t("healthPage.latestBath",{date:date(periodBaths[0].startedAt)}):t("healthPage.noBaths")}</p></div></section>;
  return <main className="space-y-6"><FeaturePageHeader icon={HeartPulse} title={t("healthPage.title")} description={t("healthPage.description")} babyName={baby?.name??null} latest={latestCandidates[0]?t("healthPage.latestActivity",{date:date(latestCandidates[0].startedAt)}):t("healthPage.noHealth")}/><StatisticsTabs period={period} onChange={setPeriod}/><QuickAddLauncher allowedTypes={["diaper","medicine","bath"]}/><section><h2 className="mb-3 text-xl font-bold text-slate-900 dark:text-white">{t("healthPage.diapers")}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={t("healthPage.latestDiaper")} value={live.secondsSinceLatest!==null?fmt(live.secondsSinceLatest*1000):"—"} icon={<Icon iconNode={diaper} className="h-4 w-4"/>}/><MetricCard label={t("statistics.totalDiapers")} value={String(historical.total)} hint={`${t("statistics.wet")}: ${historical.wet} · ${t("statistics.dirty")}: ${historical.dirty} · ${t("statistics.mixed")}: ${historical.mixed}`}/><MetricCard label={t("statistics.averageInterval")} value={historical.averageIntervalSeconds!==null?fmt(historical.averageIntervalSeconds*1000):"—"}/><MetricCard label={t("statistics.longestDiaperInterval")} value={historical.longestIntervalSeconds!==null?fmt(historical.longestIntervalSeconds*1000):"—"}/></div></section><section><h2 className="mb-3 text-xl font-bold text-slate-900 dark:text-white">{t("healthPage.medicine")}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label={t("healthPage.latestMedicine")} value={medicine[0]?.data.medicineName??"—"} hint={medicine[0]?`${medicine[0].data.dose} · ${date(medicine[0].startedAt)}`:t("healthPage.noMedicine")} icon={<Pill className="h-4 w-4"/>}/><MetricCard label={t("healthPage.medicineCount")} value={String(periodMedicine.length)}/></div></section><section><h2 className="mb-3 text-xl font-bold text-slate-900 dark:text-white">{t("healthPage.baths")}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label={t("healthPage.latestBathLabel")} value={baths[0]?date(baths[0].startedAt):"—"} icon={<Bath className="h-4 w-4"/>}/><MetricCard label={t("healthPage.bathCount")} value={String(periodBaths.length)}/><MetricCard label={t("healthPage.averageBathInterval")} value={bathAverage!==null?fmt(bathAverage):"—"}/></div></section><PremiumGate title={t("healthPage.premiumTitle")} description={t("healthPage.premiumDescription")} preview={advanced}>{advanced}</PremiumGate><FeatureHistorySection activities={activities} types={["diaper","medicine","bath"]} range={range} title={t("healthPage.history")}/></main>;
}
