/* eslint-disable react-hooks/exhaustive-deps, no-unused-expressions */
import { FileHeart, FileText, Loader2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import PremiumGate from "../../../components/premium/PremiumGate";
import { useActivityStore } from "../../../store/activityStore";
import { useBabyStore } from "../../../store/babyStore";
import { useSubscriptionStore } from "../../../store/subscriptionStore";
import { useAppSettingsStore } from "../../../store/appSettingsStore";
import { useVaccinationStore } from "../../../store/vaccinationStore";
import { useMilestoneStore } from "../../../store/milestoneStore";
import { exportDoctorReport } from "../pdf/exportDoctorReport";
import type { DoctorReportRange, DoctorReportSection } from "../model/doctorReport.types";
import { buildDoctorReport } from "../utils/buildDoctorReport";

const sectionKeys:DoctorReportSection[]=["sleep","feeding","breastfeeding","bottle","diapers","medications","bath","notes","growth","vaccinations","milestones"];
const initialSections=new Set<DoctorReportSection>(["sleep","feeding","breastfeeding","bottle","diapers","medications","bath","notes","growth","vaccinations","milestones"]);
const dateInput=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function rangeDates(range:DoctorReportRange,customStart:string,customEnd:string){const end=range==="custom"&&customEnd?new Date(`${customEnd}T23:59:59.999`):new Date();const start=range==="custom"&&customStart?new Date(`${customStart}T00:00:00`):new Date(end);start.setHours(0,0,0,0);if(range==="7d")start.setDate(start.getDate()-6);if(range==="30d")start.setDate(start.getDate()-29);return{start,end}}

export default function DoctorReportPage(){
 const settings=useAppSettingsStore(s=>s);
 const vaccinations=useVaccinationStore(s=>s.records);
 const milestoneRecords=useMilestoneStore(s=>s.records);
 const {t,i18n}=useTranslation();const babies=useBabyStore(s=>s.babies);const selectedId=useBabyStore(s=>s.selectedBabyId);const activities=useActivityStore(s=>s.activities);const premium=useSubscriptionStore(s=>s.plan)==="premium";const [babyId,setBabyId]=useState(selectedId??babies[0]?.id??"");const [range,setRange]=useState<DoctorReportRange>("7d");const [customStart,setCustomStart]=useState(dateInput(new Date()));const [customEnd,setCustomEnd]=useState(dateInput(new Date()));const [sections,setSections]=useState(new Set(initialSections));const [busy,setBusy]=useState(false);const [error,setError]=useState("");const baby=babies.find(item=>item.id===babyId)??null;const dates=rangeDates(range,customStart,customEnd);const count=activities.filter(a=>a.babyId===babyId&&new Date(a.startedAt)>=dates.start&&new Date(a.startedAt)<=dates.end).length;
 const labels=useMemo(()=>Object.fromEntries(["birthDate","age","reportPeriod","generatedAt","timeline","summary","disclaimer","sleep","totalSleep","nightSleep","daySleep","averageNap","longestNap","naps","wakeWindow","feeding","totalFeedings","latestFeeding","bottle","breastfeeding","count","totalMl","averageMl","averageDuration","diapers","wet","dirty","mixed","averagePerDay","lastChange","medications","bath","growth","growthWeight","growthHeight","growthHead","change","none","sleepRecorded","feedingRecorded","diaperRecorded","noActivities"].map(key=>[key,t(`doctorReport.labels.${key}`)])),[t,i18n.language]);
 Object.assign(labels,{birthDate:t("doctorReport.birthDate"),age:t("doctorReport.age"),reportPeriod:t("doctorReport.reportPeriod"),generatedAt:t("doctorReport.generatedAt"),timeline:t("doctorReport.timeline"),summary:t("doctorReport.aiSummary"),disclaimer:t("doctorReport.disclaimer")});
 Object.assign(labels,{growth:t("doctorReport.sections.growth"),growthWeight:t("activity.weightKg"),growthHeight:t("activity.heightCm"),growthHead:t("activity.headCircumferenceCm"),change:t("growth.change")});
 Object.assign(labels,{vaccinations:t("doctorReport.sections.vaccinations"),completedVaccinations:t("doctorReport.completedVaccinations"),dose:t("vaccinations.dose",{count:""})});
 Object.assign(labels,{currentSchedule:t("vaccinations.currentSchedule"),sourceAuthority:t("vaccinations.sourceAuthority")});
 Object.assign(labels,{milestones:t("doctorReport.sections.milestones"),chronologicalAge:t("milestones.chronologicalAge"),correctedAge:t("milestones.correctedAge"),milestoneDisclaimer:t("milestones.sourceDisclaimer"),weeks:t("babyProfile.weeks")});
 for(const record of milestoneRecords){if(record.milestoneId)labels[`milestone:${record.milestoneId}`]=t(`milestones.items.${record.milestoneId}`)}
 for(const record of vaccinations){labels[record.vaccineName]=t(record.vaccineName);labels[`vaccinations.vaccines.${record.vaccineCode}`]=t(`vaccinations.vaccines.${record.vaccineCode}`)}
 async function download(){if(!baby||!premium)return;setBusy(true);setError("");try{const period=range==="today"?"today":range==="30d"||range==="custom"?"30d":"7d";await exportDoctorReport(buildDoctorReport({baby,activities,vaccinations,milestones:milestoneRecords,start:dates.start,end:dates.end,period,sections,language:i18n.language,labels,weightUnit:settings.weightUnit,lengthUnit:settings.lengthUnit}))}catch{setError(t("doctorReport.exportError"))}finally{setBusy(false)}}
 const preview=<div className="space-y-5 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800 sm:p-7"><div className="border-b border-slate-200 pb-5 text-center dark:border-slate-700"><FileHeart className="mx-auto h-9 w-9 text-indigo-600"/><h2 className="mt-2 text-2xl font-bold text-slate-900 dark:text-white">BabyNest</h2><p className="text-sm text-slate-500">{baby?.name??t("doctorReport.noBaby")} · {dates.start.toLocaleDateString(i18n.language)} – {dates.end.toLocaleDateString(i18n.language)}</p></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><strong>{count}</strong><p className="text-xs text-slate-500">{t("doctorReport.activities")}</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><strong>{sections.size}</strong><p className="text-xs text-slate-500">{t("doctorReport.includedSections")}</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><strong>PDF</strong><p className="text-xs text-slate-500">ReportLab</p></div></div>{sectionKeys.filter(k=>sections.has(k)).map(key=><div key={key} className="rounded-xl border border-slate-200 p-3 text-sm font-semibold dark:border-slate-700">{t(`doctorReport.sections.${key}`)}</div>)}</div>;
 return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8"><section className="rounded-[2rem] bg-gradient-to-br from-indigo-700 via-indigo-600 to-cyan-600 p-7 text-white"><FileText className="h-9 w-9"/><h1 className="mt-4 text-3xl font-bold">{t("doctorReport.title")}</h1><p className="mt-2 max-w-2xl text-indigo-100">{t("doctorReport.description")}</p></section><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><aside className="space-y-5 rounded-[2rem] border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><label className="block text-sm font-semibold">{t("doctorReport.selectedBaby")}<select value={babyId} onChange={e=>setBabyId(e.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-white px-3 dark:border-slate-600 dark:bg-slate-900">{babies.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div><p className="text-sm font-semibold">{t("doctorReport.reportPeriod")}</p><div className="mt-2 grid grid-cols-2 gap-2">{(["today","7d","30d","custom"] as DoctorReportRange[]).map(value=><button key={value} onClick={()=>setRange(value)} className={`rounded-xl border px-3 py-2 text-sm ${range===value?"border-indigo-600 bg-indigo-50 text-indigo-700 dark:bg-indigo-950":"border-slate-200 dark:border-slate-700"}`}>{t(`doctorReport.ranges.${value}`)}</button>)}</div>{range==="custom"?<div className="mt-3 grid gap-2"><input aria-label={t("doctorReport.startDate")} type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)} className="h-10 rounded-xl border px-3 dark:border-slate-600 dark:bg-slate-900"/><input aria-label={t("doctorReport.endDate")} type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)} className="h-10 rounded-xl border px-3 dark:border-slate-600 dark:bg-slate-900"/></div>:null}</div><div><p className="text-sm font-semibold">{t("doctorReport.includeSection")}</p><div className="mt-2 space-y-2">{sectionKeys.map(key=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sections.has(key)} onChange={e=>setSections(current=>{const next=new Set(current);e.target.checked?next.add(key):next.delete(key);return next})}/>{t(`doctorReport.sections.${key}`)}{["growth","vaccinations"].includes(key)?<span className="text-xs text-slate-400">({t("doctorReport.future")})</span>:null}</label>)}</div></div><button disabled={!premium||!baby||busy||dates.start>dates.end} onClick={download} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileText className="h-4 w-4"/>}{t("doctorReport.exportPdf")}</button>{error?<p className="text-sm text-rose-600">{error}</p>:null}</aside><PremiumGate title={t("doctorReport.premiumTitle")} description={t("doctorReport.premiumDescription")} preview={preview}>{preview}</PremiumGate></div></main>
}
