import type { Activity } from "../../../entities/activity/model/activity.types";
import type { Baby } from "../../../entities/baby/model/baby.types";
import { calculateBabyAge, formatBabyAge } from "../../baby/utils/babyAge";
import { buildStatisticsSnapshot, formatDurationLabel, type StatisticsPeriod } from "../../utils/statistics";
import type { AppLengthUnit, AppWeightUnit } from "../../../store/appSettingsStore";
import { formatLength, formatWeight } from "../../settings/utils/formatting";
import { formatMetricChange, getGrowthActivities, getMetricSummary } from "../../growth/utils/growth";
import type { VaccinationRecord } from "../../vaccinations/model/vaccination.types";
import { getScheduleDefinition } from "../../vaccinations/data/schedules";
import { vaccinationScheduleSources } from "../../vaccinations/data/sources";
import type { BabyMilestoneRecord } from "../../milestones/model/milestone.types";
import { getMilestoneAgeSummary } from "../../milestones/utils/milestoneAge";
import type { DoctorReportPayload, DoctorReportSection } from "../model/doctorReport.types";
import { useMemoryStore } from "../../../store/memoryStore";
import i18n from "../../../i18n";

export interface DoctorReportInput { baby:Baby;activities:Activity[];vaccinations:VaccinationRecord[];milestones?:BabyMilestoneRecord[];start:Date;end:Date;period:StatisticsPeriod;sections:Set<DoctorReportSection>;language:string;labels:Record<string,string>;weightUnit:AppWeightUnit;lengthUnit:AppLengthUnit }
const valid=(value:string)=>{const time=new Date(value).getTime();return Number.isFinite(time)?time:null};
export function buildDoctorReport(input:DoctorReportInput):DoctorReportPayload{
 const {baby,start,end,language,labels,sections}=input;const activities=input.activities.filter(a=>{const time=valid(a.startedAt);return a.babyId===baby.id&&time!==null&&time>=start.getTime()&&time<=end.getTime()}).sort((a,b)=>new Date(a.startedAt).getTime()-new Date(b.startedAt).getTime());
 const snapshot=buildStatisticsSnapshot(activities,input.period,end);const rows:DoctorReportPayload["sections"]=[];const duration=(ms:number)=>formatDurationLabel(ms,language);const add=(key:DoctorReportSection,title:string,values:Array<[string,string]>)=>{if(sections.has(key))rows.push({key,title,rows:values.map(([label,value])=>({label,value}))})};
 add("sleep",labels.sleep,[[labels.totalSleep,duration(snapshot.totalSleepMilliseconds)],[labels.nightSleep,duration(snapshot.nightSleepMilliseconds)],[labels.daySleep,duration(snapshot.daySleepMilliseconds)],[labels.averageNap,duration(snapshot.averageNapDurationMilliseconds)],[labels.longestNap,duration(snapshot.longestNapMilliseconds)],[labels.naps,String(snapshot.napCount)],[labels.wakeWindow,`${snapshot.averageWakeWindowMinutes} min`]]);
 const bottles=activities.filter(a=>a.type==="bottle"),breast=activities.filter(a=>a.type==="breastfeeding");const totalMl=bottles.reduce((sum,a)=>sum+a.data.amountMl,0);const breastMs=breast.reduce((sum,a)=>sum+(a.data.leftDurationSeconds+a.data.rightDurationSeconds)*1000,0);const latestFeed=[...bottles,...breast].at(-1);
 if(sections.has("feeding"))rows.push({key:"feeding",title:labels.feeding,rows:[{label:labels.totalFeedings,value:String(bottles.length+breast.length)},{label:labels.latestFeeding,value:latestFeed?new Date(latestFeed.startedAt).toLocaleString(language):labels.none}]});
 add("bottle",labels.bottle,[[labels.count,String(bottles.length)],[labels.totalMl,`${totalMl} ml`],[labels.averageMl,`${bottles.length?Math.round(totalMl/bottles.length):0} ml`]]);add("breastfeeding",labels.breastfeeding,[[labels.count,String(breast.length)],[labels.averageDuration,duration(breast.length?breastMs/breast.length:0)]]);
 const diapers=activities.filter(a=>a.type==="diaper");add("diapers",labels.diapers,[[labels.wet,String(diapers.filter(a=>a.data.diaperType==="wet").length)],[labels.dirty,String(diapers.filter(a=>a.data.diaperType==="dirty").length)],[labels.mixed,String(diapers.filter(a=>a.data.diaperType==="mixed").length)],[labels.averagePerDay,(diapers.length/Math.max(1,Math.ceil((end.getTime()-start.getTime())/86400000))).toFixed(1)],[labels.lastChange,diapers.at(-1)?new Date(diapers.at(-1)!.startedAt).toLocaleString(language):labels.none]]);
 const medicines=activities.filter(a=>a.type==="medicine");if(sections.has("medications"))rows.push({key:"medications",title:labels.medications,rows:medicines.map(a=>({label:`${new Date(a.startedAt).toLocaleString(language)} · ${a.data.medicineName}`,value:[a.data.dose,a.note].filter(Boolean).join(" · ")}))});
 const growth=getGrowthActivities(activities,baby.id),growthRows:Array<[string,string]>=[];for(const [metric,label] of [["weightKg",labels.growthWeight],["heightCm",labels.growthHeight],["headCircumferenceCm",labels.growthHead]] as const){const summary=getMetricSummary(growth,metric);if(summary.value!==null){const value=metric==="weightKg"?formatWeight(summary.value,input.weightUnit,language):formatLength(summary.value,input.lengthUnit,language);const change=formatMetricChange(summary.change,metric,input.weightUnit,input.lengthUnit);growthRows.push([label,change?`${value} (${labels.change}: ${change})`:value])}}if(sections.has("growth"))rows.push({key:"growth",title:labels.growth,rows:[...growthRows,...growth.map(item=>[new Date(item.startedAt).toLocaleString(language),[item.data.weightKg!==undefined?formatWeight(item.data.weightKg,input.weightUnit,language):null,item.data.heightCm!==undefined?formatLength(item.data.heightCm,input.lengthUnit,language):null,item.data.headCircumferenceCm!==undefined?formatLength(item.data.headCircumferenceCm,input.lengthUnit,language):null].filter(Boolean).join(" · ")] as [string,string])].map(([label,value])=>({label,value}))});
 const timelineMap=new Map<string,string[]>();for(const a of activities){if((a.type==="bottle"&&!sections.has("bottle"))||(a.type==="breastfeeding"&&!sections.has("breastfeeding"))||(a.type==="diaper"&&!sections.has("diapers"))||(a.type==="sleep"&&!sections.has("sleep"))||(a.type==="medicine"&&!sections.has("medications"))||(a.type==="bath"&&!sections.has("bath")))continue;const date=new Date(a.startedAt);const day=date.toLocaleDateString(language,{weekday:"long",year:"numeric",month:"short",day:"numeric"});const time=date.toLocaleTimeString(language,{hour:"2-digit",minute:"2-digit"});let text:string=a.type;if(a.type==="bottle")text=`${labels.bottle} ${a.data.amountMl} ml`;if(a.type==="breastfeeding")text=labels.breastfeeding;if(a.type==="sleep")text=labels.sleep;if(a.type==="diaper")text=`${labels.diapers}: ${labels[a.data.diaperType]}`;if(a.type==="medicine")text=`${a.data.medicineName} ${a.data.dose}`;if(a.type==="bath")text=labels.bath;if(sections.has("notes")&&a.note)text+=` — ${a.note}`;timelineMap.set(day,[...(timelineMap.get(day)??[]),`${time}  ${text}`])}
 const reportSchedule=getScheduleDefinition(baby.vaccinationProfile?.countryCode??"BG",baby.vaccinationProfile?.regionCode);const reportSource=reportSchedule?vaccinationScheduleSources[reportSchedule.sourceId]:null;const completedVaccinations=input.vaccinations.filter(record=>{if(record.babyId!==baby.id||!(record.status==="completed"||record.recordOrigin==="manual"||record.recordOrigin==="imported"))return false;const date=valid(record.administeredDate??record.scheduledDate);return date!==null&&date>=start.getTime()&&date<=end.getTime()}).sort((a,b)=>new Date(a.administeredDate??a.scheduledDate).getTime()-new Date(b.administeredDate??b.scheduledDate).getTime());if(sections.has("vaccinations"))rows.push({key:"vaccinations",title:labels.vaccinations,rows:[{label:labels.currentSchedule,value:[baby.vaccinationProfile?.countryCode??"BG",baby.vaccinationProfile?.regionCode,baby.vaccinationProfile?.scheduleVersion??"BG-2026.1"].filter(Boolean).join(" · ")},...(reportSource?[{label:labels.sourceAuthority,value:`${reportSource.authority} · ${reportSource.verifiedAt}`}]:[]),...(completedVaccinations.length?completedVaccinations.map(record=>({label:`${labels[record.vaccineName]??labels[`vaccinations.vaccines.${record.vaccineCode}`]??record.vaccineCode} · ${new Date(record.administeredDate??record.scheduledDate).toLocaleDateString(language)}`,value:[`${labels.dose} ${record.doseNumber}`,record.recordOrigin,record.scheduleCountryCode,record.scheduleRegionCode,record.scheduleVersion,record.manufacturer,record.batchNumber,record.doctor,record.clinic,record.reaction,record.notes].filter(Boolean).join(" · ")})):[{label:labels.completedVaccinations,value:labels.none}])]});
 const milestoneAge=getMilestoneAgeSummary(baby,end);const reportMilestones=(input.milestones??[]).filter(record=>record.babyId===baby.id&&record.includeInDoctorReport!==false&&record.status!=="not-observed"&&record.status!=="not-applicable").filter(record=>{const date=valid(record.observedAt??record.firstNoticedAt??record.updatedAt);return date!==null&&date>=start.getTime()&&date<=end.getTime()});if(sections.has("milestones"))rows.push({key:"milestones",title:labels.milestones,rows:[{label:labels.chronologicalAge,value:`${milestoneAge.chronologicalWeeks} ${labels.weeks}`},...(milestoneAge.correctedApplicable?[{label:labels.correctedAge,value:`${milestoneAge.correctedWeeks} ${labels.weeks}`}]:[]),...reportMilestones.map(record=>({label:record.customTitle??labels[`milestone:${record.milestoneId}`]??record.milestoneId??labels.milestones,value:[record.status,record.observedAt?new Date(record.observedAt).toLocaleDateString(language):null,record.note,record.concernText].filter(Boolean).join(" · ")})),{label:labels.milestones,value:labels.milestoneDisclaimer}]});
 const reportMemories=useMemoryStore.getState().memories.filter(memory=>{const date=valid(memory.date);return memory.babyId===baby.id&&memory.visibility==="family"&&date!==null&&date>=start.getTime()&&date<=end.getTime()});if(reportMemories.length)rows.push({key:"memories",title:i18n.t("doctorReport.sections.memories",{lng:language}),rows:reportMemories.map(memory=>({label:memory.title||memory.titleKey?i18n.t(memory.title||memory.titleKey!,{lng:language}):i18n.t("memories.untitled",{lng:language}),value:[new Date(memory.date).toLocaleDateString(language),memory.description,...memory.tags.map(tag=>`#${tag}`)].filter(Boolean).join(" · ")}))});
 const summary:string[]=[];if(snapshot.totalSleepMilliseconds)summary.push(labels.sleepRecorded);if(bottles.length+breast.length)summary.push(labels.feedingRecorded);if(diapers.length)summary.push(labels.diaperRecorded);if(!activities.length&&!completedVaccinations.length)summary.push(labels.noActivities);
 return {language,baby:{name:baby.name,birthday:new Date(baby.birthday).toLocaleDateString(language),age:formatBabyAge(calculateBabyAge(baby.birthday),language)},period:{start:start.toISOString(),end:end.toISOString(),label:`${start.toLocaleDateString(language)} – ${end.toLocaleDateString(language)}`},generatedAt:new Date().toLocaleString(language),labels:{birthDate:labels.birthDate,age:labels.age,reportPeriod:labels.reportPeriod,generatedAt:labels.generatedAt,timeline:labels.timeline,summary:labels.summary,noRecords:labels.none,disclaimer:labels.disclaimer},sections:rows,timeline:[...timelineMap].map(([day,entries])=>({day,entries})),summary};
}
