begin;
create extension if not exists pgcrypto;
create schema if not exists private;

create type public.family_role as enum ('owner','parent','guardian','grandparent','babysitter','doctor','viewer');
create type public.member_status as enum ('active','invited','suspended','left');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, version integer not null default 1, client_id text);
create table public.families (id uuid primary key, name text not null check(length(name) between 1 and 120), owner_id uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, version integer not null default 1, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), client_id text);
create table public.family_members (id uuid primary key, family_id uuid not null references public.families(id), profile_id uuid not null references public.profiles(id), role public.family_role not null, status public.member_status not null default 'active', permissions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, version integer not null default 1, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), client_id text, unique(family_id,profile_id));
create table public.babies (id uuid primary key, family_id uuid not null references public.families(id), name text not null, birthday date not null, gender text not null default 'unspecified', gestational_week integer check(gestational_week between 20 and 45), data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, version integer not null default 1, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), client_id text);
create table public.activities (id uuid primary key, family_id uuid not null references public.families(id), baby_id uuid not null references public.babies(id), type text not null, started_at timestamptz not null, ended_at timestamptz, data jsonb not null default '{}'::jsonb, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, version integer not null default 1, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), client_id text);
create table public.audit_log (id uuid primary key default gen_random_uuid(), family_id uuid not null references public.families(id), actor_id uuid references public.profiles(id), entity_type text not null, entity_id uuid not null, operation text not null, old_data jsonb, new_data jsonb, created_at timestamptz not null default now(), client_id text);

create index families_updated_idx on public.families(updated_at); create index families_deleted_idx on public.families(deleted_at);
create index family_members_family_idx on public.family_members(family_id); create index family_members_updated_idx on public.family_members(family_id,updated_at); create index family_members_deleted_idx on public.family_members(deleted_at);
create index babies_family_idx on public.babies(family_id); create index babies_updated_idx on public.babies(family_id,updated_at); create index babies_deleted_idx on public.babies(deleted_at);
create index activities_family_idx on public.activities(family_id); create index activities_baby_idx on public.activities(baby_id); create index activities_started_idx on public.activities(started_at); create index activities_updated_idx on public.activities(updated_at); create index activities_deleted_idx on public.activities(deleted_at); create index activities_baby_started_idx on public.activities(baby_id,started_at); create index activities_family_updated_idx on public.activities(family_id,updated_at); create index audit_family_created_idx on public.audit_log(family_id,created_at desc);

create function private.touch_sync_row() returns trigger language plpgsql security invoker set search_path='' as $$ begin new.updated_at=now(); new.version=old.version+1; if auth.uid() is not null then new.updated_by=auth.uid(); end if; return new; end $$;
create function private.stamp_insert_actor() returns trigger language plpgsql security invoker set search_path='' as $$ begin if auth.uid() is not null then new.created_by=auth.uid(); new.updated_by=auth.uid(); end if; return new; end $$;
create trigger families_stamp before insert on public.families for each row execute function private.stamp_insert_actor(); create trigger family_members_stamp before insert on public.family_members for each row execute function private.stamp_insert_actor(); create trigger babies_stamp before insert on public.babies for each row execute function private.stamp_insert_actor(); create trigger activities_stamp before insert on public.activities for each row execute function private.stamp_insert_actor();
create trigger families_touch before update on public.families for each row execute function private.touch_sync_row();
create trigger family_members_touch before update on public.family_members for each row execute function private.touch_sync_row();
create trigger babies_touch before update on public.babies for each row execute function private.touch_sync_row();
create trigger activities_touch before update on public.activities for each row execute function private.touch_sync_row();
create function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',''),new.email) on conflict(id) do nothing; return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function private.handle_new_user();

create function private.is_family_member(target_family uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.family_members fm where fm.family_id=target_family and fm.profile_id=auth.uid() and fm.status='active' and fm.deleted_at is null) $$;
create function private.owns_family(target_family uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.family_members fm where fm.family_id=target_family and fm.profile_id=auth.uid() and fm.role='owner' and fm.status='active' and fm.deleted_at is null) $$;
create function private.is_family_owner_record(target_family uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.families f where f.id=target_family and f.owner_id=auth.uid() and f.deleted_at is null) $$;
create function private.has_family_permission(target_family uuid, permission_name text) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.family_members fm where fm.family_id=target_family and fm.profile_id=auth.uid() and fm.status='active' and fm.deleted_at is null and (fm.role='owner' or coalesce((fm.permissions->>permission_name)::boolean,false) or (permission_name='canEditActivities' and fm.role in ('parent','guardian','grandparent','babysitter')) or (permission_name='canDeleteActivities' and fm.role in ('parent','guardian')) or (permission_name='canManageBaby' and fm.role in ('parent','guardian')) or (permission_name='canManageMembers' and fm.role in ('parent','guardian')))) $$;
revoke all on all functions in schema private from public; grant usage on schema private to authenticated; grant execute on function private.is_family_member(uuid),private.owns_family(uuid),private.is_family_owner_record(uuid),private.has_family_permission(uuid,text) to authenticated;

create function private.audit_mutation() returns trigger language plpgsql security definer set search_path='' as $$ declare row_data jsonb; fam uuid; entity uuid; begin row_data=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end; fam=(row_data->>'family_id')::uuid; entity=(row_data->>'id')::uuid; insert into public.audit_log(family_id,actor_id,entity_type,entity_id,operation,old_data,new_data,client_id) values(fam,auth.uid(),tg_table_name,entity,tg_op,case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end,row_data->>'client_id'); return coalesce(new,old); end $$;
create trigger babies_audit after insert or update or delete on public.babies for each row execute function private.audit_mutation(); create trigger activities_audit after insert or update or delete on public.activities for each row execute function private.audit_mutation();

alter table public.profiles enable row level security; alter table public.families enable row level security; alter table public.family_members enable row level security; alter table public.babies enable row level security; alter table public.activities enable row level security; alter table public.audit_log enable row level security;
create policy profiles_self_select on public.profiles for select to authenticated using(id=auth.uid()); create policy profiles_self_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy families_select on public.families for select to authenticated using(owner_id=auth.uid() or private.is_family_member(id)); create policy families_insert on public.families for insert to authenticated with check(owner_id=auth.uid() and created_by=auth.uid()); create policy families_update on public.families for update to authenticated using(private.owns_family(id)) with check(private.owns_family(id));
create policy members_select on public.family_members for select to authenticated using(private.is_family_member(family_id)); create policy members_insert_owner_bootstrap on public.family_members for insert to authenticated with check((profile_id=auth.uid() and role='owner' and private.is_family_owner_record(family_id)) or private.has_family_permission(family_id,'canManageMembers')); create policy members_update on public.family_members for update to authenticated using(private.has_family_permission(family_id,'canManageMembers')) with check(private.has_family_permission(family_id,'canManageMembers'));
create policy babies_select on public.babies for select to authenticated using(private.is_family_member(family_id)); create policy babies_insert on public.babies for insert to authenticated with check(private.has_family_permission(family_id,'canManageBaby')); create policy babies_update on public.babies for update to authenticated using(private.has_family_permission(family_id,'canManageBaby')) with check(private.has_family_permission(family_id,'canManageBaby'));
create policy activities_select on public.activities for select to authenticated using(private.is_family_member(family_id)); create policy activities_insert on public.activities for insert to authenticated with check(private.has_family_permission(family_id,'canEditActivities') and exists(select 1 from public.babies b where b.id=baby_id and b.family_id=activities.family_id)); create policy activities_update on public.activities for update to authenticated using(private.has_family_permission(family_id,'canEditActivities')) with check(private.has_family_permission(family_id,'canEditActivities')); create policy activities_delete on public.activities for delete to authenticated using(private.has_family_permission(family_id,'canDeleteActivities'));
create policy audit_select on public.audit_log for select to authenticated using(private.is_family_member(family_id));
grant select,insert,update on public.profiles,public.families,public.family_members,public.babies,public.activities to authenticated; grant delete on public.activities to authenticated; grant select on public.audit_log to authenticated;
alter publication supabase_realtime add table public.family_members,public.babies,public.activities;
commit;
