import { Baby } from "lucide-react";
import { useTranslation } from "react-i18next";
import type { Activity } from "../../../entities/activity/model/activity.types";
import { useAppSettingsStore } from "../../../store/appSettingsStore";
import { formatLength, formatWeight } from "../../settings/utils/formatting";
import { formatMetricChange, getGrowthActivities, getMetricSummary } from "../../growth/utils/growth";

function Tile({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-3 dark:border-slate-700 dark:bg-slate-900/70"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold text-slate-900 dark:text-white">{value}</p></div>}
export default function GrowthSummaryCard({activities,babyId,range}:{activities:Activity[];babyId:string|null;range:{start:Date;end:Date}}){const {t,i18n}=useTranslation();const settings=useAppSettingsStore(s=>s);const records=getGrowthActivities(activities,babyId).filter(item=>{const time=new Date(item.startedAt).getTime();return time>=range.start.getTime()&&time<=range.end.getTime()});const weight=getMetricSummary(records,"weightKg"),height=getMetricSummary(records,"heightCm"),head=getMetricSummary(records,"headCircumferenceCm");const latest=records[0]??null;const days=latest?Math.max(0,Math.floor((Date.now()-new Date(latest.startedAt).getTime())/86400000)):null;const change=(value:number|null,metric:"weightKg"|"heightCm"|"headCircumferenceCm")=>formatMetricChange(value,metric,settings.weightUnit,settings.lengthUnit)??t("statistics.notAvailable");return <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800 sm:p-6"><div className="inline-flex items-center gap-2 rounded-full bg-sky-100 px-3 py-1 text-sm font-semibold text-sky-700"><Baby className="h-4 w-4"/>{t("statistics.growth")}</div><h2 className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">{t("statistics.growthSummary")}</h2>{records.length?<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Tile label={t("growth.measurementCount")} value={String(records.length)}/><Tile label={t("statistics.latestWeight")} value={weight.value!==null?formatWeight(weight.value,settings.weightUnit,i18n.language):t("statistics.notAvailable")}/><Tile label={t("statistics.latestHeight")} value={height.value!==null?formatLength(height.value,settings.lengthUnit,i18n.language):t("statistics.notAvailable")}/><Tile label={t("statistics.latestHeadCircumference")} value={head.value!==null?formatLength(head.value,settings.lengthUnit,i18n.language):t("statistics.notAvailable")}/><Tile label={t("growth.weightTrend")} value={change(weight.change,"weightKg")}/><Tile label={t("growth.heightTrend")} value={change(height.change,"heightCm")}/><Tile label={t("growth.headTrend")} value={change(head.change,"headCircumferenceCm")}/><Tile label={t("growth.daysSinceLatest")} value={days===null?t("statistics.notAvailable"):String(days)}/></div>:<div className="mt-6 rounded-2xl border border-dashed border-slate-300 p-8 text-center text-slate-500 dark:border-slate-700">{t("growth.noMeasurements")}</div>}</section>}
