import type{Activity}from"../../../entities/activity/model/activity.types";import type{Baby}from"../../../entities/baby/model/baby.types";import{babyNestDb}from"../../../lib/local-db/babyNestDb";import{requireSupabase}from"../../../lib/supabase/supabaseClient";import{activityToRow,babyToRow}from"../../../data/remote/supabaseMappers";
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const MAP_KEY="babynest-cloud-migration-map";export interface MigrationCounts{babies:number;activities:number}export interface MigrationBackup{createdAt:string;babies:Baby[];activities:Activity[];localStorageData:Record<string,string>}
function idMap(ids:string[]){const saved=JSON.parse(localStorage.getItem(MAP_KEY)||"{}")as Record<string,string>;for(const id of ids)if(!saved[id])saved[id]=uuid.test(id)?id:crypto.randomUUID();localStorage.setItem(MAP_KEY,JSON.stringify(saved));return saved}
export function createLocalBackup(babies:Baby[],activities:Activity[]):MigrationBackup{const keys=Object.keys(localStorage).filter(key=>key.startsWith("babynest-"));const backup={createdAt:new Date().toISOString(),babies,activities,localStorageData:Object.fromEntries(keys.map(key=>[key,localStorage.getItem(key)??""]))};localStorage.setItem("babynest-cloud-migration-backup",JSON.stringify(backup));return backup}
export function downloadMigrationBackup(backup:MigrationBackup){const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`babynest-cloud-backup-${backup.createdAt.slice(0,10)}.json`;link.click();URL.revokeObjectURL(url)}
export async function createCloudFamily(name:string){const client=requireSupabase();const{data:{user}}=await client.auth.getUser();if(!user)throw new Error("AUTH_REQUIRED");const familyId=crypto.randomUUID();const memberId=crypto.randomUUID();const{error:familyError}=await client.from("families").insert({id:familyId,name,owner_id:user.id,created_by:user.id,updated_by:user.id,client_id:getDeviceId()});if(familyError)throw familyError;const{error:memberError}=await client.from("family_members").insert({id:memberId,family_id:familyId,profile_id:user.id,role:"owner",status:"active",created_by:user.id,updated_by:user.id,client_id:getDeviceId()});if(memberError)throw memberError;return familyId}
export function getDeviceId(){let id=localStorage.getItem("babynest-device-id");if(!id){id=crypto.randomUUID();localStorage.setItem("babynest-device-id",id)}return id}
export async function migrateLocalData(input:{familyId:string;babies:Baby[];activities:Activity[];signal?:AbortSignal;onProgress?:(done:number,total:number)=>void}){const client=requireSupabase();const map=idMap([...input.babies.map(item=>item.id),...input.activities.map(item=>item.id)]);const total=input.babies.length+input.activities.length;let done=0;for(const batch of chunks(input.babies,100)){if(input.signal?.aborted)throw new DOMException("Cancelled","AbortError");const rows=batch.map(baby=>babyToRow({...baby,id:map[baby.id]},input.familyId,getDeviceId()));const{error}=await client.from("babies").upsert(rows,{onConflict:"id"});if(error)throw error;done+=batch.length;input.onProgress?.(done,total)}for(const batch of chunks(input.activities,100)){if(input.signal?.aborted)throw new DOMException("Cancelled","AbortError");const rows=batch.map(activity=>activityToRow({...activity,id:map[activity.id],babyId:map[activity.babyId],familyId:input.familyId},input.familyId,getDeviceId()));const{error}=await client.from("activities").upsert(rows as never,{onConflict:"id"});if(error)throw error;done+=batch.length;input.onProgress?.(done,total)}const[{count:babyCount,error:babyError},{count:activityCount,error:activityError}]=await Promise.all([client.from("babies").select("id",{count:"exact",head:true}).eq("family_id",input.familyId).is("deleted_at",null),client.from("activities").select("id",{count:"exact",head:true}).eq("family_id",input.familyId).is("deleted_at",null)]);if(babyError||activityError||babyCount!<input.babies.length||activityCount!<input.activities.length)throw new Error("MIGRATION_COUNT_MISMATCH");await babyNestDb.syncState.put({id:"cloud",enabled:true,familyId:input.familyId,lastSuccessfulSyncAt:new Date().toISOString()});return{babies:babyCount??0,activities:activityCount??0}}
function chunks<T>(values:T[],size:number){const result:T[][]=[];for(let index=0;index<values.length;index+=size)result.push(values.slice(index,index+size));return result}
